# Generated by Django 4.2.1 on 2023-05-26 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatroom_invite_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='joined_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='left_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
