# Generated by Django 4.2.1 on 2023-05-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_groupmember_joined_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmember',
            old_name='users',
            new_name='user',
        ),
    ]
