# Generated by Django 4.2.1 on 2023-05-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_users_groupmember_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='color',
            new_name='color_session',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_photo',
            new_name='photo',
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('MESSAGE', 'message'), ('JOIN', 'join'), ('LEAVE', 'leave')], default='MESSAGE', max_length=10),
        ),
    ]
