# Generated by Django 4.2.1 on 2023-05-27 23:27

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_chatroom_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='color_session',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.get_upload_profile_path),
        ),
    ]
